# -*- coding: utf-8 -*-
"""scrapping.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pz04hzTqDTvW2j7OnhbxufbcTKK41AqL
"""

from google_play_scraper import reviews, Sort
import pandas as pd

result, _ = reviews(
    'com.gojek.app',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=12000
)

df = pd.DataFrame(result)[['content', 'score']]

df.to_csv("gojek_reviews_12000.csv", index=False)

print("Dataset berhasil disimpan dengan total data:", len(df))